import { Action } from '../../types';

export const ACTION_CATALOG: { type: Action['type']; label: string; description: string; icon?: string }[] = [
    { type: 'click', label: 'Click', description: 'Click an element', icon: 'ads_click' },
    { type: 'check', label: 'Check', description: 'Ensure a checkbox is checked', icon: 'check_box' },
    { type: 'uncheck', label: 'Uncheck', description: 'Ensure a checkbox is unchecked', icon: 'check_box_outline_blank' },
    { type: 'drag_and_drop', label: 'Drag and Drop', description: 'Drag an element to a target', icon: 'drag_indicator' },
    { type: 'reload', label: 'Reload', description: 'Reload the current page', icon: 'refresh' },
    { type: 'select', label: 'Select', description: 'Select an option from a menu', icon: 'arrow_drop_down_circle' },
    { type: 'type', label: 'Type', description: 'Type text into a field', icon: 'text_format' },
    { type: 'hover', label: 'Hover', description: 'Hover an element', icon: 'my_location' },
    { type: 'press', label: 'Press', description: 'Press a key', icon: 'keyboard' },
    { type: 'wait', label: 'Wait', description: 'Pause for seconds', icon: 'schedule' },
    { type: 'wait_selector', label: 'Wait for Selector', description: 'Wait until element appears', icon: 'schedule' },
    { type: 'wait_downloads', label: 'Wait for Downloads', description: 'Wait until downloads finish', icon: 'download' },
    { type: 'scroll', label: 'Scroll', description: 'Scroll the page or container', icon: 'swap_vert' },
    { type: 'javascript', label: 'JavaScript', description: 'Run custom JS', icon: 'javascript' },
    { type: 'csv', label: 'CSV', description: 'Parse CSV into rows', icon: 'csv' },
    { type: 'upload', label: 'Upload', description: 'Upload latest cabinet item', icon: 'upload_file' },
    { type: 'finalize_uploads', label: 'Finalize Uploads', description: 'Mark this run’s uploads complete', icon: 'task_alt' },
    { type: 'merge', label: 'Merge', description: 'Merge inputs into a single output', icon: 'layers' },
    { type: 'screenshot', label: 'Screenshot', description: 'Capture a screenshot', icon: 'photo_camera' },
    { type: 'navigate', label: 'Navigate To', description: 'Navigate to a URL', icon: 'navigation' },
    { type: 'if', label: 'If', description: 'Conditional block start', icon: 'call_split' },
    { type: 'else', label: 'Else', description: 'Conditional alternate path', icon: 'call_split' },
    { type: 'end', label: 'End Block', description: 'Close a block', icon: 'subdirectory_arrow_right' },
    { type: 'while', label: 'While', description: 'Loop while condition true', icon: 'repeat' },
    { type: 'repeat', label: 'Repeat N', description: 'Repeat block N times', icon: 'repeat' },
    { type: 'foreach', label: 'For Each', description: 'Loop through items', icon: 'list' },
    { type: 'set', label: 'Set Variable', description: 'Update variable value', icon: 'variable_insert' },
    { type: 'stop', label: 'Stop Task', description: 'Stop task with status', icon: 'stop' },
    { type: 'on_error', label: 'On Error', description: 'Run on failure', icon: 'warning' },
    { type: 'start', label: 'Start Task', description: 'Run another task', icon: 'play_circle' },
    { type: 'http_request', label: 'HTTP Request', description: 'Make an API call', icon: 'language' },
    { type: 'get_content', label: 'Get Content', description: 'Get page or element text content', icon: 'article' },
    { type: 'solve_captcha', label: 'Solve Captcha', description: 'Solve through a compatible remote endpoint or the active-browser local solver', icon: 'verified_user' },
    { type: 'wait_captcha', label: 'Wait for Captcha', description: 'Wait until a captcha interaction is ready', icon: 'hourglass_top' },
    { type: 'do_nothing', label: 'Do Nothing', description: 'No operation block', icon: 'block' }
];
